# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gimchi}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Junegunn Choi"]
  s.date = %q{2011-04-08}
  s.description = %q{Gimchi knows how to pronounce Korean strings and how to write them in roman alphabet.}
  s.email = %q{junegunn.c@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.ko.rdoc",
    "README.rdoc"
  ]
  s.files = [
    "config/default.yml",
    "lib/gimchi.rb",
    "lib/gimchi/char.rb",
    "lib/gimchi/korean.rb",
    "lib/gimchi/patch_1.8.rb",
    "lib/gimchi/pronouncer.rb"
  ]
  s.homepage = %q{http://github.com/junegunn/gimchi}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Gimchi reads Korean.}
  s.test_files = [
    "test/helper.rb",
    "test/pronunciation.yml",
    "test/romanization.yml",
    "test/test_gimchi.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ansi>, [">= 1.2.2"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ansi>, [">= 1.2.2"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ansi>, [">= 1.2.2"])
  end
end

